### PR TITLE
[JENKINS-63971] prepare for casc support of node monitors

### PR DESCRIPTION
**Pull request by mawinter69**
to support node monitors in casc, is is essential that they have DataBoundConstructors defined and a proper symbol is used.

### Testing done
Tested with https://github.com/jenkinsci/configuration-as-code-plugin/pull/2392 that the monitors are properly exported and can be imported.

export looks like this:
```
nodeMonitors:
  - diskSpaceMonitor:
      freeSpaceThreshold: "3GB"
  - tmpSpace:
      freeSpaceThreshold: "3GB"
  - jvmVersion:
      comparisonMode: EXACT_MATCH
      disconnect: true
  - inodesMonitor:
      inodesPercentThreshold: "98%"
  - remotingVersion:
      ignored: true
```

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
This looks great to me.  Thanks very much.  I need to test it before I merge it.  That may take a few days because I am currently traveling and won't return until the end of the week.

**Comment by jonesbusy** [comment]
Thanks as well. Adding JCasC support for for nodeMonitor is a must.

I was testing similar changes when implementing #192 and I confirm changes in the descriptor behave as expected

**Comment by MarkEWaite** [comment]
I've confirmed that with the configuration as code pull request and this pull request, I see the configuration as code entries.  The configuration as code pull request is required before the results of this pull request will be visible to users.

**Comment by MarkEWaite** [comment]
I've marked this pull request as a draft because the required pull configuration as code pull request is a draft.

* https://github.com/jenkinsci/configuration-as-code-plugin/pull/2392

**Comment by mawinter69** [comment]
@MarkEWaite can this be merged now?

**Comment by MarkEWaite** [comment]
Yes.  Thanks for the pull request @mawinter69 !

**Pull request merged**
